# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  bioc-release
sudo: false
cache: packages

os:
  - linux
  - osx

r_packages:
  - covr

# safe list
branches:
  only:
  - master

after_success:
  - Rscript -e 'library(covr); codecov()'
