# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
sudo: false
cache: packages

os:
  - linux
  - osx

bioc_packages:
  - zlibbioc
  - Rhtslib

r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - RcppProgress
  - ape
  - R6
  - knitr
  - testthat

r_packages:
  - covr

# safe list
branches:
  only:
  - master

after_success:
  - Rscript -e 'library(covr); codecov()'
