# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
sudo: false
cache: packages

os:
  - linux
  - osx

r_packages:
  - covr

# safe list
branches:
  only:
  - master

# For MacOSX systems
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install xz || ( brew update && brew install xz ); fi

after_success:
  - Rscript -e 'library(covr); codecov()'
